sayinglist = [
[' 사랑에 의해 행해지는 것은 언제나 선악을 초월한다. ', 'What is done out of love always takes place beyond good and evil.', '프레드리히 니체', 'Friedrich Nietzsche'], 
[' 누군가를 사랑한다는 것은 자신을 그와 동일시 하는 것이다. ', 'To love someone is to identify with them.', '아리스토텔레스', 'Aristotle'], 
[' 사랑 받고 싶다면 사랑하라, 그리고 사랑스럽게 행동하라. ', 'If you would be loved, love and be lovable.', '벤자민 프랭클린', 'Benjamin Franklin'], 
[' 사랑은 증오의 소음을 덮어버리는 쿵쾅대는 큰 북소리다. ', 'Love is the big booming beat which covers up the noise of hate.', '마가릿 조', 'Margaret Cho'], 
[' 단지 누구를 사랑한다고 해서 무조건 감싸야 한다는 뜻은 아니다. 사랑은 상처를 덮는 붕대가 아니다. ', "Just because you love someone doesn't mean you have to be involved with them. Love is not a bandage to cover wounds.", '휴 엘리어트', 'Hugh Elliott'], 
[' 사랑이란 한 사람과 다른 모든 사람들간 차이의 심각한 과장이다. ', 'Love is a gross exaggeration of the difference between one person and everyone else.', '윌리엄 셰익스피어', 'William Shakespeare'], 
[' 우리를 인정해주는 사람들을 어떻게 소중히 여기고 존경할까! ', 'How we treasure (and admire) the people who acknowledge us!', '줄리 모건스턴', 'Julie Morgenstern'], 
[' 너희들이 나만큼 인생에 대해 알게 되면 강박적인 사랑의 힘을 과소평가하진 않을 게다. ', 'When you have seen as much of life as I have, you will not underestimate the power of obsessive love.', 'J. R. R. 톨킨', 'J. R. R. Tolkien'], 
[' 멀리 있는 사람을 사랑하기는 쉽다. 가까이 있는 사람을 사랑하기란 항상 쉬운 것만은 아니다. 기아로부터 사람들을 구제하기 위해서 한 움큼의 쌀을 주는 것이 자신의 집에 있는 이의 외로움과 고통을 덜어주는 것보다 더 쉽다. 당신의 집에 사랑을 가져다 주어라. 가정이야말로 우리의 사랑이 시작되는 곳이어야 하기 때문이다. ', 'It is easy to love the people far away. It is not always easy to love those close to us. It is easier to give a cup of rice to relieve hunger than to relieve the loneliness and pain of someone unloved in our home. Bring love into your home for this is where our love for each other must start.', '마더 테레사', 'Mother Teresa'], 
[' 한 여자에 대해 생각해봐. 그 여자는 네가 자기에 대해 생각하는지 몰라. 네가 그 여자 생각을 하든 말든 상관 안해. 그러면 넌 더욱 더 그 여자 생각을 하게되지. ', "Think about a woman. Doesn't know you're thinking about her. Doesn't care you're thinking about her. Makes you think about her even more.", '마틴 세이지', 'Martin Sage'], 
[' 과도한 사랑은 인간에게 아무런 명예나 가치도 가져다주지 않는다. ', 'When love is in excess it brings a man no honor nor worthiness.', '에우리피데스', 'Euripides'], 
[' 겁쟁이는 사랑을 드러낼 능력이 없다. 사랑은 용기있는 자의 특권이다. ', 'A coward is incapable of exhibiting love; it is the prerogative of the brave.', '마하트마 간디', 'Mahatma Gandhi'], 
[' 공상 속의 사랑이 현실의 사랑보다 훨씬 좋다. 사랑하지 않는 것은 매우 자극적이다. 가장 자극적인 매력은 결코 만나지 않는 양극 간에 존재한다. ', 'Fantasy love is much better than reality love. Never doing it is very exciting. The most exciting attractions are between two opposites that never meet.', '앤디 워홀', 'Andy Warhol'], 
[' 세기의 사랑일지라도 참고 견뎌내야 한다. ', 'Great loves too must be endured.', '가브리엘(코코)샤넬', 'Gabriel Coco Chanel'], 
[' 난 여자의 감정을 농락하는 남자를 좋게 생각할 수 없어. 종종 남들이 생각하는 것보다 훨씬 더 많이 상처 받을 수 있거든. ', "I cannot think well of a man who sports with any woman's feelings; and there may often be a great deal more suffered than a stander-by can judge of.", '제인 오스틴', 'Jane Austen'], 
[' 오직 남을 위해 산 인생만이 가치있는 것이다. ', 'Only a life lived for others is a life worth while.', '알버트 아인슈타인', 'Albert Einstein'], 
[' 강렬한 사랑은 판단하지 않는다. 주기만 할 뿐이다. ', 'Intense love does not measure, it just gives.', '마더 테레사', 'Mother Teresa'], 
[' 사랑은 존재하거나 존재하지 않는다. 가벼운 사랑은 아예 사랑이 아니다. ', "Love is or it ain't. Thin love ain't love at all.", '토니 모리슨', 'Toni Morrison'], 
[' 실제로 느끼지 못하는 사랑을 느끼는 척 하지 말라. 사랑은 우리가 좌지우지 할 수 없으므로 ', 'Never pretend to a love which you do not actually feel, for love is not ours to command.', '앨런 왓츠', 'Alan Watts'], 
[' 사랑은 끝없는 용서의 행위이며, 습관으로 굳어지는 상냥한 표정이다. ', 'Love is an act of endless forgiveness, a tender look which becomes a habit.', '해브록 엘리스', 'Havelock Ellis'],
[' 인생이란 누구나 한 번쯤 시도해 볼 만한 것이다. ', 'Life is something that everyone should try at least once.', '헨리 J. 틸만', 'Henry J. Tillman'],
[' 20대에 당신의 얼굴은 자연이 준 것이지만, 50대의 당신의 얼굴은 스스로 가치를 만들어야 한다. ', 'Nature gives you the face you have at twenty; it is up to you to merit the face you have at fifty.', '가브리엘(코코)샤넬', 'Gabriel Coco Chanel'],
[' 출생과 죽음은 피할 수 없으므로 그 사이를 즐겨라. ', 'There is no cure for birth and death, save to enjoy the interval.', '조지 산타야나', 'George Santayana'],
[' 인생은 외국어이다. 모든 사람이 그것을 잘못 발음한다. ', 'Life is a foreign language; all men mispronounce it.', '크리스토퍼 몰리', 'Christopher Morley'],
[' 어른이 된다는 건 착한 아이로 지낸다고 받는 상이 아니야. 승진이나 월급 인상이나 마찬가지로, 어른 대접을 받기 위해 노력하면서 몇 년을 허비할 수도 있어. 조금만 더 노력한다면, 조금만 더 착하게 행동한다면… 하고 말이야. 아니, 어른이 된다는 건 네가 차지해야만 하는 거야. 스스로에게 주는 거지. ', "Adulthood isn't an award they'll give you for being a good child. You can waste... years, trying to get someone to give that respect to you, as though it were a sort of promotion or raise in pay. If only you do enough, if only you are good enough. No. You have to just... take it. Give it to yourself, I suppose.", '로이스 맥마스터 부욜', 'Lois McMaster Bujold'],
[' 여행은 되돌아 보았을 때에만 매력적이다. ', 'Travel is only glamorous in retrospect.', '폴 서룩스', 'Paul Theroux'],
[' 인생은 본래 녹록지 않다. 하지만 멍청한 사람에게는 더욱 녹록지 않다. ', "Life is tough, but it's tougher when you're stupid.", '존 웨인', 'John Wayne'],
[' 자신이 어떻게 변해왔는지 알려면 변하지 않은 곳으로 돌아가는 것보다 더 좋은 방법은 없다. ', 'There is nothing like returning to a place that remains unchanged to find the ways in which you yourself have altered.', '넬슨 만델라', 'Nelson Mandela'],
[' 젊은이를 타락으로 이끄는 확실한 방법은 다르게 생각하는 사람 대신 같은 사고방식을 가진 이를 존경하도록 지시하는 것이다. ', 'The surest way to corrupt a youth is to instruct him to hold in higher esteem those who think alike than those who think differently.', '프레드리히 니체', 'Friedrich Nietzsche'],
[' 인생에는 서두르는 것 말고도 더 많은 것이 있다. ', 'There is more to life than increasing its speed', '마하트마 간디', 'Mahatma Gandhi'],
[' 우리는 젊을 때에 배우고 나이가 들어서 이해한다. ', 'In youth we learn; in age we understand.', '마리 폰 에브너 에셴바흐', 'Marie Ebner von Eschenbach'],
[' 인생이 진지하다는 증거는 털끝만큼도 없다. ', 'Not a shred of evidence exists in favor of the idea that life is serious.', '브렌단 길', 'Brendan Gill'],
[' 우리 중 아무도, 심지어 우리 중 가장 어린 사람도 잘못이 없지 않다. ', 'We are none of us infallible--not even the youngest of us.', 'W. H. 톰슨', 'W. H. Thompson'],
[' 안전이란 대개 미신이다. 그것은 사실상 존재하지 않는다… 인생은 대담한 모험이거나 아니면 아무것도 아니다. ', 'Security is mostly a superstition. It does not exist in nature.... Life is either a daring adventure or nothing.', '헬렌 켈러', 'Helen Keller'],
[' 인생이란 결코 공평하지 않다. 이 사실에 익숙해져라. ', 'Life is not fair; get used to it.', '빌 게이츠', 'Bill Gates'],
[' 20세에 보수주의자가 되는 것은 무정한 것이고 60세에 진보주의자가 되는 것은 정말 어리석은 것이다. ', 'To be conservative at 20 is heartless and to be a liberal at 60 is plain idiocy.', '윈스턴 처칠', 'Sir Winston Churchill'],
[' 자신에 대한 정의를 바꿀 만큼 심대한 변화는 단순히 삶과 사고 방식의 사소한 변화가 아닌, 총체적 탈태(脫態)를 요구한다. ', 'Any transition serious enough to alter your definition of self will require not just small adjustments in your way of living and thinking but a full-on metamorphosis.', '마사 베크', 'Martha Beck'],
[' 어린 시절 우리는 어른이 되면 더 이상 나약하지 않을 거라 생각했다. 하지만 어른이 된다는 것은 나약함을 받아들이는 것이다. 살아있다는 것은 나약하다는 것이다. ', 'When we were children, we used to think that when we were grown-up we would no longer be vulnerable. But to grow up is to accept vulnerability... To be alive is to be vulnerable.', '매들린 랭글', "Madeleine L'Engle"],
[' 사람들이 너를 내버려두면 삶은 아름다울 거야 ', 'Life could be wonderful if people would leave you alone.', '찰리 채플린', 'Charlie Chaplin'],
[' 때로는 살아있는 것조차도 용기가 될 때가 있다. ', 'Sometimes even to live is an act of courage.', '세네카', 'Seneca'],
[' 배우고 때로 익히면 또한 기쁘지 아니한가 (學而時習之 不亦說乎 / 학이시습지 불역열호) ', "Isn't it a pleasure to study, and to practice what you have learned?", '공자', 'Confucius'],
[' 훌륭한 가르침은 1/4이 준비 과정, 3/4은 현장에서 이루어진다. ', 'Good teaching is one-fourth preparation and three-fourths theater.', '게일 고드윈', 'Gail Godwin'],
[' 모든 인간의 행동은 기회, 천성, 충동, 습관, 이성, 열정, 욕망의 일곱 가지 중 한 가지 이상이 그 원인이 된다. ', 'All human actions have one or more of these seven causes: chance, nature, compulsion, habit, reason, passion, and desire.', '아리스토텔레스', 'Aristotle'],
[' 교육은 일종의 계속되는 대화이고, 그 대화는 세상일이 보통 그렇듯 여러 가지 관점이 있음을 인정한다. ', 'Education is a kind of continuing dialogue, and a dialogue assumes, in the nature of the case, different points of view.', '로버트 허친스', 'Robert Hutchins'],
[' 우리가 해야할 일은 끊임없이 호기심을 갖고 새로운 생각을 시험해보고 새로운 인상을 받는 것이다. ', 'What we have to do is to be forever curiously testing new opinions and courting new impressions.', '월터 페이터', 'Walter Pater'],
[' 배우기만 하고 생각하지 않으면 얻는 것이 없고, 생각만 하고 배우지 않으면 위태롭다. ', 'He who learns but does not think, is lost! He who thinks but does not learn is in great danger.', '공자', 'Confucius'],
[' 행동이 비열하고 하찮다면 그 정신이 자랑스럽고 의로울 수 없습니다. 사람의 행동이야말로 그의 정신이기 때문입니다. ', "You cannot have a proud and chivalrous spirit if your conduct is mean and paltry; for whatever a man's actions are, such must be his spirit.", '데모스테네스', 'Demosthenes'],       
[' 어려운 직업에서 성공하려면 자신을 굳게 믿어야 한다. 이것이 탁월한 재능을 지닌 사람보다 재능은 평범하지만 강한 투지를 가진 사람이 훨씬 더 성공하는 이유다. ', 'Getting ahead in a difficult profession requires avid faith in yourself. That is why some people with mediocre talent, but with great inner drive, go much further than people with vastly superior talent.', '소피아 로렌', 'Sophia Loren'],
[' 배움은 의무도, 생존도 아니다. ', 'Learning is not compulsory... neither is survival.', '에드워즈 데밍', 'W. Edwards Deming'],
[' 교육은 최상의 노후 대비책이다. ', 'Education is the best provision for old age.', '아리스토텔레스', 'Aristotle'],
[' 군자는 말하기 전에 행동하고, 그후 자신의 행동에 맞춰 말을 한다. ', 'The superior man acts before he speaks, and afterwards speaks according to his action.', '공자', 'Confucius'],
[' 실천이 말보다 낫다. ', 'Well done is better than well said.', '벤자민 프랭클린', 'Benjamin Franklin'],
[' 아이들이 답이 있는 질문을 하기 시작하면 그들이 성장하고 있음을 알 수 있다. ', 'You know that children are growing up when they start asking questions that have answers.', '존 J. 플롬프', 'John J. Plomp'],
[' 군자는 말은 어눌해도 행동에는 민첩하다. ', 'The superior man is modest in his speech, but excels in his actions.', '공자', 'Confucius'],
[' 목적없는 공부는 기억에 해가 될 뿐이며, 머리속에 들어온 어떤 것도 간직하지 못한다. ', 'Study without desire spoils the memory, and it retains nothing that it takes in.', '레오나르도 다빈치', 'Leonardo da Vinci'],
[' 더 많이 준다고 아이를 망치는 게 아니다. 충돌을 피하려고 더 많이 주면 아이를 망친다. ', 'It is not giving children more that spoils them; it is giving them more to avoid confrontation.', '존 그레이', 'John Gray'],
[' 교육이라는 기술은 그저 젊은이들의 자연스런 호기심을 깨우는 기술로, 나중에 그 호기심을 충족시키는 것이 목적이다 ', 'The whole art of teaching is only the art of awakening the natural curiosity of young minds for the purpose of satisfying it afterwards.', '아나톨 프랑스', 'Anatole France'],
[' 백만 가지 사실을 머릿속에 집어넣고도 여전히 완전히 무지할 수 있다. ', 'It is possible to store the mind with a million facts and still be entirely uneducated.', '알렉 본', 'Alec Bourne'],
[' 어떤 생각에 동의하지 않고도 그 생각을 해볼 수 있는 것이 교육받은 사람의 특징이다. ', 'It is the mark of an educated mind to be able to entertain a thought without accepting it.', '아리스토텔레스', 'Aristotle'],
[' 남의 말을 따라하기 위해서는 교육이 필요하다. 그 말에 도전하기 위해서는 두뇌가 필요하다. ', 'To repeat what others have said, requires education; to challenge it, requires brains.', '메리 페티본 풀', 'Mary Pettibone Poole'],
[' 기운과 끈기는 모든 것을 이겨낸다. ', 'Energy and persistence conquer all things.', '벤자민 프랭클린', 'Benjamin Franklin'],
[' 완벽이 아닌 성공을 목표로 하라. 틀릴 권리를 결코 포기하지 마라. 그러면 살면서 새로운 것을 배워 앞으로 나아갈 능력을 잃기 때문이다. ', 'Aim for success, not perfection. Never give up your right to be wrong, because then you will lose the ability to learn new things and move forward with your life.', '데이비드 M. 번즈', 'Dr. David M. Burns'],
[' 자신이 성공하는 내면의 그림을 마음속에 명확히 그리고 지울 수 없게 각인시켜라. 이 그림을 끈질기게 간직하라. 절대 희미해지도록 내버려두지 마라. 그대의 마음이 이 그림을 실현하기 위해 노력할 것이다. 당신의 상상속에 어떠한 장애물도 두지 마라. ', 'Formulate and stamp indelibly on your mind a mental picture of yourself as succeeding. Hold this picture tenaciously. Never permit it to fade. Your mind will seek to develop the picture...Do not build up obstacles in your imagination.', '노먼 빈센트 필', 'Norman Vincent Peale'],
[' 모든 성공은 더 어려운 문제로 가는 입장권을 사는 것일 뿐이다. ', 'Each success only buys an admission ticket to a more difficult problem.', '헨리 키신저', 'Henry Kissinger'],
[' 성공은 열심히 노력하며 기다리는 사람에게 찾아온다. ', 'Everything comes to him who hustles while he waits.', '토마스 A. 에디슨', 'Thomas A. Edison'],
[' 기회를 찾아야 기회를 만든다. ', 'You create your opportunities by asking for them.', '패티 헨슨', 'Patty Hansen'],
[' 팀에는 내가 없지만 팀의 승리에는 내가 있다 (Team이란 단어에는 I 자가 없지만 win이란 단어에는 있다.) ', 'There is no "i" in team but there is in win.', '마이클 조던', 'Michael Jordan'],
[' 성공은 자연연소의 결과가 아니다. 먼저 자기 자신에게 불을 지펴야 한다. ', 'Success is not the result of spontaneous combustion. You must set yourself on fire.', '레기 리치', 'Reggie Leach'],
[' 가장 잠재력있는 뮤즈는 우리 안에 있는 어린아이다. ', 'The most potent muse of all is our own inner child.', '스티븐 나흐마노비치', 'Stephen Nachmanovitch'],
[' 운은 계획에서 비롯된다. ', 'Luck is the residue of design.', '브랜치 리키', 'Branch Rickey'],
[' 일하여 얻으라. 그러면 운명의 바퀴를 붙들어 잡은 것이다. ', 'Work and acquire, and thou hast chained the wheel of Chance.', '랄프 왈도 에머슨', 'Ralph Waldo Emerson'],
[' 언제나 현재에 집중할 수 있다면 행복할 것이다. ', "If you can concentrate always on the present, you'll be a happy man.", '파울로 코엘료', 'Paulo Cuelho'],
[' 주가 변동을 적으로 보지말고 친구로 보라. 어리석음에 동참하지말고 오히려 그것을 이용해서 이익을 내라. ', 'Look at market fluctuations as your friend rather than your enemy; profit from folly rather than participate in it.', '워런 버핏', 'Warren Buffett'],
[' 사업의 성공은 훈련과 절도, 고된 노력을 요한다. 그러나 이런 것들에 지레 겁먹지만 않으면 성공의 기회는 오늘도 그 어느 때 못지 않다. ', "Success in business requires training and discipline and hard work. But if you're not frightened by these things, the opportunities are just as great today as they ever were.", '데이비드 록펠러', 'David Rockefeller'],
[' 어디에든 교황 같은 사람들이 있다. 물론 그들은 특정 역할을 한다. 그들은 우리를 물질적으로 지원해준다. 그러나 어떤 것도 창조하지 않는 이들이기에 예술가의 창작 활동을 막을 수 있도록 해서는 안된다. ', "There were always people like the pope. They serve a certain function, of course. They subsidize us. But, they don't create anything and they must never be allowed to stop the artist from creating.", '다이앤 프롤로브', 'Diane Frolov'],
[' 관찰하는데 있어서는 준비된 자에게만 기회가 온다. ', 'In the field of observation, chance favors only the prepared mind.', '루이 파스퇴르', 'Louis Pasteur'],
[' 실패하는 것은 곧 성공으로 한 발짝 더 나아가는 것이다. ', 'People fail forward to success.', '메리 케이 애쉬', 'Mary Kay Ash'],
[' 나에게 창의성은 안먹고는 살 수 없는 약과 같다. ', 'Creativity is a drug I cannot live without.', '세실 B. 드밀', 'Cecil B. DeMille'],
[' 기회가 찾아오는 정확한 때와 장소를 알아보고 그 기회를 잡을 수 있어야 한다. 세상에 기회는 많다. 그저 손 놓고 앉아 있을 수는 없다. ', "You have to recognize when the right place and the right time fuse and take advantage of that opportunity. There are plenty of opportunities out there. You can't sit back and wait.", '엘렌 멧칼프', 'Ellen Metcalf'],
[' 인생에 있는 큰 비밀은 큰 비밀 따위는 없다는 것이다. 당신의 목표가 무엇이든 열심히 할 의지가 있다면 달성할 수 있다. ', "The big secret in life is that there is no big secret. Whatever your goal, you can get there if you're willing to work.", '오프라 윈프리', 'Oprah Winfrey'],
[' 어머니는 낯선 사람이란 없으며, 아직 만나지 않은 친구가 있을 뿐이라고 말씀 하셨다. 어머니는 지금 호주에서 최고 보안시설의 치매노인요양소에 계시다. ', "My mother used to say that there are no strangers, only friends you haven't met yet. She's now in a maximum security twilight home in Australia.", '데임 에드나 에브리지', 'Dame Edna Everage'],
[' 진정한 행복은 잘 드러나지 않으며, 화려함과 소란스러움을 적대시한다. 진정한 행복은 처음에는 자신의 삶을 즐기는데서, 다음에는 몇몇 선택된 친구와의 우정과 대화에서 온다. ', "True happiness is of a retired nature, and an enemy to pomp and noise; it arises, in the first place, from the enjoyment of one's self, and in the next from the friendship and conversation of a few select companions.", '조지프 애디슨', 'Joseph Addison'],
[' 우정을 끝낼 수 있다면 그 우정은 실제로 존재하지 않은 것이다. ', 'The friendship that can cease has never been real.', '성 제롬', 'Saint Jerome'],
[' 우정이 깊어지는 것을 거부하지 말라. 열에 아홉이 아무것도 가져다 주지 않을 때, 나머지 하나가 되돌려 줄 수 있으니. ', 'Never refuse any advance of friendship, for if nine out of ten bring you nothing, one alone may repay you.', '탕생 부인', 'Madame de Tencin'],
[' 역경은 누가 진정한 친구인지 가르쳐준다. ', 'Adversity does teach who your real friends are.', '로이스 맥마스터 부욜', 'Lois McMaster Bujold'],
[' 인생에서 인간이 가질 수 있는 모든 것은 가족과 친구라는 것을 알게 되었다. 이들을 잃게 되면 당신에겐 아무것도 남지 않는다. 따라서 친구를 세상 그 어떤 것 보다 더 소중하게 여겨야 한다. ', "I've learned that all a person has in life is family and friends. If you lose those, you have nothing, so friends are to be treasured more than anything else in the world.", '트레이 파커', 'Trey Parker'],
[' 누군가는 성공하고 누군가는 실수할 수도 있다. 하지만 이런 차이에 너무 집착하지 말라. 타인과 함께, 타인을 통해서 협력할 때에야 비로소 위대한 것이 탄생한다. ', 'One man may hit the mark, another blunder; but heed not these distinctions. Only from the alliance of the one, working with and through the other, are great things born.', '생텍쥐페리', 'Antoine de Saint-Exupery'],
[' 자신의 벗을 최선의 적으로 삼아야 한다. 그대의 벗과 적대할 때 그대의 마음은 벗을 더없이 가깝게 여겨야 한다. ', 'In a friend one should have ones best enemy. You should be closest to him with your heart when you resist him.', '프레드리히 니체', 'Friedrich Nietzsche'],
[' 우정이라는 기계에 잘 정제된 예의라는 기름을 바르는 것은 현명하다. ', 'It is wise to apply the oil of refined politeness to the mechanisms of friendship.', '콜레트', 'Colette'],
[' 모두에게 친절하되, 소수와 가까워지고 그 소수를 신뢰하기 전에 먼저 잘 시험해 보라. 진정한 우정이란 천천히 자라는 식물 같아서 이름을 지어주기 전에 역경을 겪고, 이겨내야만 한다. ', 'Be courteous to all, but intimate with few, and let those few be well tried before you give them your confidence. True friendship is a plant of slow growth, and must undergo and withstand the shocks of adversity before it is entitled to the appellation.', '조지 워싱턴', 'George Washington'],
[' 새벽 4시에 전화를 걸 수 있는 친구라면 중요한 친구이다. ', "It's the friends you can call up at four a.m. that matter.", '마를렌 디트리히', 'Marlene Dietrich'],
[' 친구를 얻는 방법은 친구에게 부탁을 들어달라고 하는 것이 아니라 내가 부탁을 들어주는 것이다. ', 'We secure our friends not by accepting favors but by doing them.', '투키디데스', 'Thucydides'],
[' 뭉치면 서고, 갈라지면 넘어진다. ', 'United we stand, divided we fall.', '이솝', 'Aesop'],
[' 전화번호부를 뒤져 전화를 걸고 차로 공항에 데려다 달라고 부탁하라. 데려다 주는 사람이 당신의 진정한 친구다. 나머지는 나쁜 사람은 아니다. 그저 지인일뿐이다. ', "Go through your phone book, call people and ask them to drive you to the airport. The ones who will drive you are your true friends. The rest aren't bad people; they're just acquaintances.", '제이 레노', 'Jay Leno'],
[' 친구라고 해서 불쾌한 말을 해도 된다고 생각하지 말라. 누군가와 가까운 관계가 될수록, 현명하고 예의 바르게 행동하는 것이 중요하다. 가끔 부득이한 경우를 제외하고, 친구로 하여금 불쾌한 말은 적에게서 듣게 놔두라. 적들은 이미 그런 말을 거리낌 없이 할 준비가 되어있다. ', "Don't flatter yourself that friendship authorizes you to say disagreeable things to your intimates. The nearer you come into relation with a person, the more necessary do tact and courtesy become. Except in cases of necessity, which are rare, leave your friend to learn unpleasant things from his enemies; they are ready enough to tell them.", '올리버 웬델 홈스', 'Oliver Wendell Holmes'],
[' 불행은 누가 진정한 친구가 아닌지를 보여준다. ', 'Misfortune shows those who are not really friends.', '아리스토텔레스', 'Aristotle'],
[' 가끔 우정의 척도는 피해를 주지 않는 능력이 아니라, 너의 잘못을 용서하고, 자신의 잘못에 용서를 구하는 능력이다. ', "Sometimes the measure of friendship isn't your ability to not harm but your capacity to forgive the things done to you and ask forgiveness for your own mistakes.", '랜디 K. 멀홀랜드', 'Randy K. Milholland'],
[' 친구는 있다가도 없고, 없다가도 있을 수 있지만, 적은 계속 는다. ', 'Friends may come and go, but enemies accumulate.', '토마스 존스', 'Thomas Jones'],
[' 설명하지마라--친구라면 설명할 필요가 없고, 적이라면 어차피 당신을 믿으려 하지 않을테니까. ', 'Never explain--your friends do not need it and your enemies will not believe you anyway.', '엘버트 허버드', 'Elbert Hubbard'],
[' 우리의 비평가들은 우리의 친구들이다, 그들은 우리에게 우리의 잘못을 보여주기 때문이다. ', 'Our critics are our friends; they show us our faults.', '벤자민 프랭클린', 'Benjamin Franklin'],
[' 훌륭한 건축물을 아침 햇살에 비춰보고 정오에 보고 달빛에도 비춰보아야 하듯이 진정으로 훌륭한 책은 유년기에 읽고 청년기에 다시 읽고 노년기에 또 다시 읽어야 한다. ', 'A truly great book should be read in youth, again in maturity and once more in old age, as a fine building should be seen by morning light, at noon and by moonlight.', '로버트슨 데이비스', 'Robertson Davies'],
[' 가장 발전한 문명사회에서도 책은 최고의 기쁨을 준다. 독서의 기쁨을 아는 자는 재난에 맞설 방편을 얻은 것이다. ', 'In the highest civilization, the book is still the highest delight. He who has once known its satisfactions is provided with a resource against calamity.', '랄프 왈도 에머슨', 'Ralph Waldo Emerson'],
[' 문학은 나의 이상향이다. 여기에서는 내 권리를 박탈당하지 않는다. 감각의 어떠한 장애물도 달콤하고 우아한 내 책 친구들의 이야기로부터 나를 차단하지 않는다. 그들은 나에게 곤란함이나 어색함없이 이야기한다. ', 'Literature is my Utopia. Here I am not disenfranchised. No barrier of the senses shuts me out from the sweet, gracious discourses of my book friends. They talk to me without embarrassment or awkwardness.', '헬렌 켈러', 'Helen Keller'],
[" 가끔씩 뉴욕 파티에서 신간서적에 대하여 나누는 대화 종류가 있다. 이제는 이런 말 자체도 진부해진 '진부하다'라는 말이 나올 때가 있다. 당신은 '편집이 덜 되었다'고 하고 나는 '신선미가 떨어진다'고 한다. 다양한 문학 비평에 대하여 대화는 끊임없이 이어지고 대화가 진전될 때 쯤이면 한 가지는 분명하다. 책을 읽은 사람은 아무도 없고 모두들 서평만 읽었다. ", 'There\'s a certain kind of conversation you have from time to time at parties in New York about a new book. The word "banal" sometimes rears its by-now banal head; you say "underedited," I say "derivative." The conversation goes around and around various literary criticisms, and by the time it moves on one thing is clear: No one read the book; we just read the reviews.', '안나 퀸드랜', 'Anna Quindlen'],
[' 제인 오스틴의 책에서 누락된 내용만으로도 책 한 권 없던 도서관을 꽤 좋은 도서관으로 만들 수 있을 것이다. ', "Just the omission of Jane Austen's books alone would make a fairly good library out of a library that hadn't a book in it.", '마크 트웨인', 'Mark Twain'],
[' 책으로 한 나라의 상당 부분을 다닐 수 있다. ', 'You can cover a great deal of country in books.', '앤드루 랭', 'Andrew Lang'],
[' 책의 수는 점점 늘어날 것이고, 사람은 책에서 무언가를 배우는 것이 우주 전체를 직접 연구하는 데서 배우는 것과 비슷한 정도로 어려워질 때가 올 것을 예견할 수 있다. 자연에 숨어있는 진실의 일부를 탐구하는 것이 방대한 수의 책에 숨겨진 진실을 탐색하는 것과 비슷하게 편해질 것이다. ', 'The number of books will grow continually, and one can predict that a time will come when it will be almost as difficult to learn anything from books as from the direct study of the whole universe. It will be almost as convenient to search for some bit of truth concealed in nature as it will be to find it hidden away in an immense multitude of bound volumes.', '드니 디드로', 'Denis Diderot'],
[' 책들은… 바닷가재 껍질과도 같아서 우리는 자신을 책으로 감싼 후 뚫고 자라나 초기 성장단계들의 증거로 뒤에 남긴다. ', "Books...are like lobster shells, we surround ourselves with 'em, then we grow out of 'em and leave 'em behind, as evidence of our earlier stages of development.", '도로시 세이어즈', 'Dorothy L. Sayers'],
[' 좋은 소설은 그 소설의 영웅에 대한 진실을 우리에게 알려준다. 그러나 나쁜 소설은 그 소설의 작가에 대한 진실을 우리에게 알려준다. ', 'A good novel tells us the truth about its hero; but a bad novel tells us the truth about its author.', 'G. K. 체스터튼', 'G. K. Chesterton'],
[' 읽는 것 만큼 쓰는 것을 통해서도 많이 배운다. ', 'Learn as much by writing as by reading.', '액톤 경', 'Lord Acton'],
[' 책 한 권 읽기를 간절히 바라는 사람과 읽을 만한 책을 기다리다 지친 사람 사이에는 매우 큰 차이가 있다. ', 'There is a great deal of difference between an eager man who wants to read a book and the tired man who wants a book to read.', 'G. K. 체스터튼', 'G. K. Chesterton'],
[' 제멋대로 골랐다는 불평을 하지 말고 먼저 소설을 집어 들어야 하는 유일한 이유는 그것이 재밌을 것이기 때문이다. ', 'The only obligation to which in advance we may hold a novel, without incurring the accusation of being arbitrary, is that it be interesting.', '헨리 제임스', 'Henry James'],
[' 사실 우리는 힘을 얻기 위해 독서해야 한다. 독서하는 자는 극도로 활기차야 한다. 책은 손 안의 한 줄기 빛이어야 한다. ', "Properly, we should read for power. Man reading should be man intensely alive. The book should be a ball of light in one's hand.", '에즈라 파운드', 'Ezra Pound'],
[' 일정 연령이 지나면 독서는 창의적인 추구로부터 마음을 너무 멀어지게 만든다. 너무 많이 읽고 자신의 뇌를 너무 적게 쓰는 사람은 누구나 게으른 사고 습관에 빠진다. ', 'Reading, after a certain age, diverts the mind too much from its creative pursuits. Any man who reads too much and uses his own brain too little falls into lazy habits of thinking.', '알버트 아인슈타인', 'Albert Einstein'],
[' 한 권의 책을 읽음으로써 자신의 삶에서 새 시대를 본 사람이 너무나 많다. ', 'How many a man has dated a new era in his life from the reading of a book.', '헨리 데이비드 소로우', 'Henry David Thoreau'],
[' 서점 만큼 인간의 심성이 그토록 약해지는 곳이 어디 있는가? ', 'Where is human nature so weak as in the bookstore?', '헨리 워드 비처', 'Henry Ward Beecher'],
[' 반박하거나 오류를 찾아내려고 책을 읽지 말고 이야기와 담화를 찾아내려고도 읽지 말며 단지 숙고하고 고려하기 위하여 읽으라. ', 'Read not to contradict and confute, nor to find talk and discourse, but to weigh and consider.', '프랜시스 베이컨', 'Sir Francis Bacon'],
[' 때때로 독서는 생각하지 않기 위한 기발한 수단이다. ', 'Reading is sometimes an ingenious device for avoiding thought.', '아서 헬프스', 'Sir Arthur Helps'],
[' 개를 제외하고 책은 인간의 가장 좋은 친구다. 개에 푹 빠져 있으면 독서를 할 수 없다. ', "Outside of a dog, a book is man's best friend. Inside of a dog it's too dark to read.", '그루초 마르크스', 'Groucho Marx'],
[' 단순히 읽기 시작했다는 이유만으로 결코 책을 끝까지 읽지 말라. ', 'Never read a book through merely because you have begun it.', '존 위더스푼', 'John Witherspoon'],
[' 떠날 때가 되었으니, 이제 각자의 길을 가자. 나는 죽기 위해서, 당신들은 살기 위해. 어느 편이 더 좋은 지는 오직 신만이 알 뿐이다. ', 'The hour of departure has arrived, and we go our ways - I to die, and you to live. Which is better God only knows.', '소크라테스', 'Socrates'],
[' 인간의 감정은 누군가를 만날 때와 헤어질 때 가장 순수하며 가장 빛난다. ', "Man's feelings are always purest and most glowing in the hour of meeting and of farewell.", '장 폴 리히터', 'Jean Paul Richter'],
[' 이별의 아픔 속에서만 사랑의 깊이를 알게 된다. ', 'Only in the agony of parting do we look into the depths of love.', '조지 앨리엇', 'George Eliot'],
[' 당신을 만나는 모든 사람이 당신과 헤어질 때는 더 나아지고 더 행복해질 수 있도록 하라. ', 'Let no one ever come to you without leaving better and happier.', '마더 테레사', 'Mother Teresa'],
[' 멀리있는 친구만큼 세상을 넓어 보이게 하는 것은 없다. 그들은 위도와 경도가 된다. ', 'Nothing makes the earth seem so spacious as to have friends at a distance; they make the latitudes and longitudes.', '헨리 데이비드 소로우', 'Henry David Thoreau'],
[' 수마일의 거리가 당신과 친구를 떼어놓을 수도 있다… 하지만 사랑하는 누군가와 정말 함께 있고 싶다면, 이미 거기 가있지 않겠는가? ', "Can miles truly separate you from friends.... If you want to be with someone you love, aren't you already there?", '리처드 바크', 'Richard Bach'],
[' 이 사랑의 꽃봉오리는 여름날 바람에 마냥 부풀었다가, 다음 만날 때엔 예쁘게 꽃필 거예요. ', "This bud of love, by summer's ripening breath, May prove a beauteous flower when next we meet.", '윌리엄 셰익스피어', 'William Shakespeare'],
[' 작별 인사에 낙담하지 말라. 재회에 앞서 작별은 필요하다. 그리고 친구라면 잠시 혹은 오랜 뒤라도 꼭 재회하게 될 터이니. ', "Don't be dismayed at goodbyes, a farewell is necessary before you can meet again and meeting again, after moments or lifetimes, is certain for those who are friends.", '리처드 바크', 'Richard Bach'],
[' 과거를 애절하게 들여다보지 마라. 다시 오지 않는다. 현재를 현명하게 개선하라. 너의 것이니. 어렴풋한 미래를 나아가 맞으라. 두려움 없이. ', 'Look not mournfully into the past. It comes not back again. Wisely improve the present. It is thine. Go forth to meet the shadowy future, without fear.', '헨리 워즈워스 롱펠로우', 'Henry Wadsworth Longfellow'],
[' 과거에서 멀어질수록 나 자신의 인격 형성에 더 가까워진다. ', 'The farther behind I leave the past, the closer I am to forging my own character.', '이자벨 에버하트', 'Isabelle Eberhardt'],
[' 나는 과거 속에 사는 편인데 내 생애 대부분이 거기 있기 때문이다. ', 'I tend to live in the past because most of my life is there.', '허브 캐언', 'Herb Caen'],
[' 현재뿐 아니라 미래까지 걱정한다면 인생은 살 가치가 없을 것이다. ', "Life wouldn't be worth living if I worried over the future as well as the present.", '윌리엄 서머셋 모옴', 'William Somerset Maugham'],
[' 일부 과학자들에 따르면 미래는 과거와 똑같을 것이다. 단지 훨씬 값비쌀 뿐이다. ', 'The future, according to some scientists, will be exactly like the past, only far more expensive.', '존 슬라덱', 'John Sladek'],
[' 시간은 만물을 스러지게 한다. 만물은 시간의 힘 아래 서서히 나이들고 시간이 흐르면서 잊혀진다. ', 'Time crumbles things; everything grows old under the power of Time and is forgotten through the lapse of Time.', '아리스토텔레스', 'Aristotle'],
[' 과거의 사건들은 크게, 십중팔구 아예 일어나지 않았던 일과 중요하지 않은 일로 나눌 수 있을 것이다. ', 'Events in the past may be roughly divided into those which probably never happened and those which do not matter.', '윌리엄 랄프 인지', 'William Ralph Inge'],
[" 프랑스의 위대한 육군원수 리요테는 어느날 정원사에게 나무를 한그루 심으라고 했다. 정원사는 그 나무는 성장이 더디기 때문에 다 자라려면 100년은 걸린다며 반대했다. 리요테는 이렇게 대답했다. '그렇다면 지체할 시간이 없네. 오늘 오후에 당장 심게!' ", "The great French Marshall Lyautey once asked his gardener to plant a tree. The gardener objected that the tree was slow growing and would not reach maturity for 100 years. The Marshall replied, 'In that case, there is no time to lose; plant it this afternoon!'", '존 F. 케네디', 'John F. Kennedy'],
[' 미래의 제국은 마음의 제국이다. ', 'The empires of the future are the empires of the mind.', '윈스턴 처칠', 'Sir Winston Churchill'],
[' 미래는 예전의 미래가 아니다. ', "The future ain't what it used to be.", '요기 베라', 'Yogi Berra'],
[' 한 순간을 위해 내가 가진 모든 것을. (한 순간만 더 살수 있다면 내가 가진 모든 것을 내놓을텐데) ', 'All my possessions for a moment of time.', '엘리자베스 1세', 'Elizabeth I'],
[' 여가시간을 가지려면 시간을 잘 써라. ', 'Employ thy time well, if thou meanest to get leisure.', '벤자민 프랭클린', 'Benjamin Franklin'],
[' 나는 당신에게 러시아의 행동을 예측해줄 수 없소. 그것은 불가사의 속의 미스터리로 포장된 수수께끼요. 그렇지만 아마 답은 있을 거요. 그 답은 러시아의 국익이오. ', 'I cannot forecast to you the action of Russia. It is a riddle wrapped in a mystery inside an enigma: but perhaps there is a key. That key is Russian national interest.', '윈스턴 처칠', 'Sir Winston Churchill'],
[' 우리가 진정으로 소유하는 것은 시간 뿐이다. 가진 것이 달리 아무 것도 없는 이에게도 시간은 있다. ', 'All that really belongs to us is time; even he who has nothing else has that.', '발타사르 그라시안', 'Baltasar Gracian'],
[' 우리는 오늘은 이러고 있지만, 내일은 어떻게 될지 누가 알아요? ', 'We know what we are, but not what we may be.', '윌리엄 셰익스피어', 'William Shakespeare'],
[' 낭비한 시간에 대한 후회는 더 큰 시간 낭비이다. ', 'Regret for wasted time is more wasted time.', '메이슨 쿨리', 'Mason Cooley'],
[' 지붕은 햇빛이 밝을 때 수리해야 합니다. ', 'The time to repair the roof is when the sun is shining.', '존 F. 케네디', 'John F. Kennedy'],
[' 나는 과거를 생각하지 않습니다. 중요한것은 끝없는 현재 뿐이지요. ', "I don't think of the past. The only thing that matters is the everlasting present.", '윌리엄 서머셋 모옴', 'William Somerset Maugham'],
[' 미래는 현재와 무척 닮았다. 단지 더 길뿐이다. ', 'The future is much like the present, only longer.', '댄 퀸스베리', 'Dan Quisenberry'],
[' 시간은 예전의 우리를 앗아가는 무자비한 도둑이다. 우리는 죽음만큼이나 삶때문에 많은 것을 잃는다. ', 'Time is a cruel thief to rob us of our former selves. We lose as much to life as we do to death.', '엘리자베스 포사이스 헤일리', 'Elizabeth Forsythe Hailey'],
[' 우리가 하는 일은 바다에 붓는 한 방울의 물보다 하찮은 것이다. 하지만 그 한 방울이 없다면 바다는 그만큼 줄어들 것이다. ', 'What we do is less than a drop in the ocean. But if it were missing, the ocean would lack something.', '마더 테레사', 'Mother Teresa'],
[' 티끌 모아 태산 ', 'The man who moves a mountain begins by carrying away small stones.', '공자', 'Confucius'],
[' 그 어떤 것에서라도 내적인 도움과 위안을 찾을 수 있다면 그것을 잡아라. ', 'As long as you derive inner help and comfort from anything, keep it.', '마하트마 간디', 'Mahatma Gandhi'],
[' 지금 적극적으로 실행되는 괜찮은 계획이 다음 주의 완벽한 계획보다 낫다. ', 'A good plan, violently executed now, is better than a perfect plan next week.', '조지 S. 패튼', 'George S. Patton'],
[' 쉽게 빠져나가는 방법은 없다. 있었다면 그 방법을 썼을 거다. 정말이지, 그런 방법은 내가 가장 좋아하는 것 중 하나일 거다! ', "There's no easy way out. If there were, I would have bought it. And believe me, it would be one of my favorite things!", '오프라 윈프리', 'Oprah Winfrey'],
[' 나는 노아의 법칙을 위반했다. 비를 예측하는 것은 중요하지 않지만, 방주를 만드는 것은 중요하다. ', "I violated the Noah rule: Predicting rain doesn't count; building arks does.", '워런 버핏', 'Warren Buffett'],
[' 누구나 노틸러스 헬스기구를 보게 되면, 이 기구의 원형이 분명히 고문이 외교에 대한 합리적 대안이었던 시절에 발명되었다는 내 의견에 동의할 것이다. ', 'I think that anyone who comes upon a Nautilus machine suddenly will agree with me that its prototype was clearly invented at some time in history when torture was considered a reasonable alternative to diplomacy.', '안나 퀸드랜', 'Anna Quindlen'],
[' 우리가 할 수 있는 최선을 다할 때, 우리 혹은 타인의 삶에 어떤 기적이 나타나는지 아무도 모른다. ', 'When we do the best that we can, we never know what miracle is wrought in our life, or in the life of another.', '헬렌 켈러', 'Helen Keller'],
[' 나에게 말하라... 그러면 나는 잊을 것이요, 나를 가르치라... 그러면 나는 배울 것이요, 나를 열중시키라... 그러면 나는 기억할 것이다. ', 'Tell me and I forget. Teach me and I remember. Involve me and I learn.', '벤자민 프랭클린', 'Benjamin Franklin'],
[' 절대 허송세월 하지마라. 책을 읽든지, 쓰든지, 기도를 하든지, 명상을 하든지, 또는 공익을 위해 노력하든지, 항상 뭔가를 해라. ', 'Never be entirely idle; but either be reading, or writing, or praying or meditating or endeavoring something for the public good.', '토마스 아 켐피스', 'Thomas a Kempis'],
[' 성공한 사람이 아니라 가치있는 사람이 되기 위해 힘쓰라. ', 'Try not to become a man of success but rather try to become a man of value.', '알버트 아인슈타인', 'Albert Einstein'],
[' 당신의 노력을 존중하라. 당신 자신을 존중하라. 자존감은 자제력을 낳는다. 이 둘을 모두 겸비하면, 진정한 힘을 갖게 된다. ', "Respect your efforts, respect yourself. Self-respect leads to self-discipline. When you have both firmly under your belt, that's real power.", '클린트 이스트우드', 'Clint Eastwood'],
[' 나는 똑똑한 것이 아니라 단지 문제를 더 오래 연구할 뿐이다. ', "It's not that I'm so smart , it's just that I stay with problems longer.", '알버트 아인슈타인', 'Albert Einstein'],
[' 사람의 생명을 구하는 것은 오직 한 걸음을 내딛는 것이다. 그리고 또 한 걸음. 항상 같은 걸음일지라도 내딛어야 한다. ', 'What saves a man is to take a step. Then another step. It is always the same step, but you have to take it.', '생텍쥐페리', 'Antoine de Saint-Exupery'],
[' 노력 없이 쓰인 글은 대개 감흥 없이 읽힌다. ', 'What is written without effort is in general read without pleasure.', '사무엘 존슨', 'Samuel Johnson'],
[' 제우스신은 모든 인간의 계획을 성취시키지 않는다. ', "Zeus does not bring all men's plans to fulfillment.", '호메로스', 'Homer'],
[' 허송세월하며 할 일이 없는 사람은 악(惡)으로 끌려가는 것이 아니라 저절로 기울어 진다. ', 'Idleness and lack of occupation tend - nay are dragged - towards evil.', '히포크라테스', 'Hippocrates'],
[' 우리가 할 수 있기 전에 배워야 하는 일들을, 우리는 하면서 배운다. ', 'For the things we have to learn before we can do them, we learn by doing them.', '아리스토텔레스', 'Aristotle'],
[' 매일 아침 하루 일과를 계획하고 그 계획을 실행하는 사람은, 극도로 바쁜 미로 같은 삶 속에서 그를 안내할 한 올의 실을 지니고 있는 것이다. 그러나 계획이 서있지 않고 단순히 우발적으로 시간을 사용하게 된다면, 곧 무질서가 삶을 지배할 것이다. ', 'He who every morning plans the transaction of the day and follows out that plan, carries a thread that will guide him through the maze of the most busy life. But where no plan is laid, where the disposal of time is surrendered merely to the chance of incidence, chaos will soon reign.', '빅터 위고', 'Victor Hugo'],
[' 이 세상의 유일한 악마는 우리 마음에서 날뛰고 있기에, 모든 전투를 마음 속에서 싸워야 한다. ', 'The only devils in this world are those running around in our own hearts, and that is where all our battles should be fought.', '마하트마 간디', 'Mahatma Gandhi'],
[' 신이 인간에게 미래를 밝혀주실 그날까지 인간의 모든 지혜는 오직 다음 두 마디 속에 있다는 것을 잊지 마십시오. 기다려라! 그리고 희망을 가져라! ', "Until the day when God shall deign to reveal the future to man, all human wisdom is summed up in these two words,--'Wait and hope'.", '알렉상드르 뒤마', 'Alexandre Dumas'],
[' 희망은 어떤 상황에서도 필요하다. ', 'Hope is necessary in every condition.', '사무엘 존슨', 'Samuel Johnson'],
[' 낙관론이 가장 많이 꽃피는 곳은 정신병원이다. ', 'The place where optimism most flourishes is the lunatic asylum.', '해브록 엘리스', 'Havelock Ellis'],
[' 어젯밤 10파운드짜리 마시멜로를 먹는 꿈을 꾸었는데, 깨어보니 베개가 사라지고 없었다. ', 'Last night I dreamed I ate a ten-pound marshmallow, and when I woke up the pillow was gone.', '토미 쿠퍼', 'Tommy Cooper'],
[' 삶의 핵심은, 그것도 긍정주의자로 사는 삶의 핵심은 아직 최상의 미래가 도래하지 않았다고 믿을 정도로 순진해지는 것이다. ', 'The point of living and of being an optimist, is to be foolish enough to believe the best is yet to come.', '해브록 엘리스', 'Havelock Ellis'],
[' 희망을 품지 않은 자는 절망도 할 수 없다. ', 'He who has never hoped can never despair.', '조지 버나드 쇼', 'George Bernard Shaw'],
[' 웃을 수 있을 때 언제든 웃어라. 공짜 보약이다. ', 'Always laugh when you can. It is cheap medicine.', '바이런', 'Lord Byron'],
[' 걱정거리를 두고 웃는 법을 배우지 못하면 나이가 들었을 때 웃을 일이 전혀 없을 것이다. ', "If you don't learn to laugh at trouble, you won't have anything to laugh at when you're old.", '에드가 왓슨 하우', 'Edgar Watson Howe'],
[' 위대한 성취를 하려면 행동하는 것뿐만 아니라, 꿈꾸는 것도 반드시 필요하다. ', 'To accomplish great things, we must dream as well as act.', '아나톨 프랑스', 'Anatole France'],
[' 이 인생에서는 마지막에 웃는 자가 가장 오래 웃는 자다. ', 'In this life he laughs longest who laughs last.', '존 메이스필드', 'John Masefield'],
[' 희망은 백일몽이다. ', 'Hope is a waking dream.', '아리스토텔레스', 'Aristotle'],
[' 우리에게는 존재하지 않는 것들을 꿈꿀 수 있는 사람들이 필요하다. ', 'We need men who can dream of things that never were.', '존 F. 케네디', 'John F. Kennedy'],
[' 어떤 일 하나에 절망하는 이는 겁쟁이다. 하지만 인류의 상태에 대해 희망을 갖는 자는 바보다. ', 'He who despairs over an event is a coward, but he who holds hope for the human condition is a fool.', '알베르 카뮈', 'Albert Camus'],
[' 아마도 인간이 가장 원하는 일들이 가장 할만한 가치가 있는 일들일 것이다. ', 'The things that one most wants to do are the things that are probably most worth doing.', '위니프레드 홀트비', 'Winifred Holtby'],
[' 타인을 이렇게도 좋게 생각하는 이유는 자신의 미래가 두렵기 때문이다. 긍정적 사고의 기저에는 끔찍한 공포가 있다. ', 'The reason we all like to think so well of others is that we are all afraid for ourselves. The basis of optimism is sheer terror.', '오스카 와일드', 'Oscar Wilde'],
[' 낙관주의는 성공으로 인도하는 믿음이다. 희망과 자신감이 없으면 아무것도 이루어질 수 없다. ', 'Optimism is the faith that leads to achievement. Nothing can be done without hope and confidence.', '헬렌 켈러', 'Helen Keller'],
[' 사람이 유머감각이 있는 게 아니다. 유머 감각이 사람을 움직이는 것이다. ', "One doesn't have a sense of humor. It has you.", '래리 겔바트', 'Larry Gelbart'],
[' 낙관론자는 우리가 최고의 세상에서 살고 있다고 주장하고 비관론자는 그 말이 사실일지도 모른다고 걱정한다. ', 'The optimist proclaims that we live in the best of all possible worlds; and the pessimist fears this is true.', '제임스 브랜치 캐벌', 'James Branch Cabell'],
[' 호레이쇼, 천지간에는 자네의 철학으로 상상하는 것보다 많은 것들이 있다네. ', 'There are more things in heaven and earth, Horatio, Than are dreamt of in your philosophy.', '윌리엄 셰익스피어', 'William Shakespeare'],
[' 무엇을 비웃는가보다 한 인간의 성격을 더 잘 보여주는 것은 없다. ', "Nothing shows a man's character more than what he laughs at.", '요한 볼프강 폰 괴테', 'Johann Wolfgang von Goethe'],
[' 세상의 중요한 업적 중 대부분은, 희망이 보이지 않는 상황에서도 끊임없이 도전한 사람들이 이룬 것이다. ', 'Most of the important things in the world have been accomplished by people who have kept on trying when there seemed to be no hope at all.', '데일 카네기', 'Dale Carnegie'],
[' 위인이나 위인의 조건에 대한 논쟁으로 시간을 낭비말라. 스스로 위인이 되라. ', 'Waste no more time talking about great souls and how they should be. Become one yourself!', '마르쿠스 아우렐리우스 안토니우스', 'Marcus Aurelius Antoninus'],
[' 다이아몬드를 찾는 사람이 진흙과 수렁에서 분투해야하는 이유는 이미 다듬어진 돌 속에서는 찾을 수 없기 때문이다. 다이아몬드는 만들어지는 것이다. ', 'He who finds diamonds must grapple in mud and mire because diamonds are not found in polished stones. They are made.', '헨리 B. 윌슨', 'Henry B. Wilson'],
[' 나는 삶에서 언제나 치열함을 추구하라고, 삶을 만끽하라고 배웠다. ', 'I had learnt to seek intensity more of life, a concentrated sense of life.', '니나 베르베로바', 'Nina Berberova'],
[" 현재 어떤 존재가 될 수 없다면 나는 될 수 있을 법한 존재가 되련다. 될 수 있을 법한 존재란 별을 향해 뻗어나가는 '아마도'의 존재이기 때문이다. 나는 '-가 됐을 뻔 했던' 사람보다는 '-이었던' 사람이 되겠다. '됐을 뻔 했던' 사람은 한 번도 그 존재가 돼 보지 못했으나 '-이었던' 사람은 한 때 그 존재로 살아봤기 때문이다. ", "I'd rather be a could - be if I cannot be an are; because a could - be is a maybe who is reaching for a star, I'd rather be a has - been than a might - have - been, by far; for a might have - been has never been, but a has was once an are.", '밀턴 벌리', 'Milton Berle'],
[' 열정으로 통치하긴 하지만, 결코 현명하게 통치하지는 못한다. ', 'Passion governs, and she never governs wisely.', '벤자민 프랭클린', 'Benjamin Franklin'],
[' 나는 결국 실패할 대의를 추구하여 승리하기보다는 결국 승리할 대의를 따르다 실패하겠다. ', 'I would rather fail in a cause that will ultimately triumph than to triumph in a cause that will ultimately fail.', '우드로 윌슨', 'Woodrow Wilson'],
[' 위대한 업적은 대개 커다란 위험을 감수한 결과이다. ', 'Great deeds are usually wrought at great risks.', '헤로도토스', 'Herodotus'],
[' 마음의 역할은 욕망에 충실하는 것이다. 마음은 주인인 열정에 헌신해야 한다. ', "It's the soul's duty to be loyal to its own desires. It must abandon itself to its master passion.", '레베카 웨스트', 'Rebecca West'],
[' 나를 믿어라. 인생에서 최대의 성과와 기쁨을 수확하는 비결은 위험한 삶을 사는 데 있다. ', 'Believe me: the secret for harvesting from existence the greatest fruitfulness and greatest enjoyment is - to live dangerously.', '프레드리히 니체', 'Friedrich Nietzsche'],
[' 모든 고귀한 일은 찾기 드문만큼 하기도 어렵다. ', 'All noble things are as difficult as they are rare.', '바뤼흐 스피노자', 'Baruch Spinoza'],
[' 너무 멀리 갈 위험을 감수하는 자만이 얼마나 멀리 갈 수 있는 지 알 수 있다. ', 'Only those who will risk going too far can possibly find out how far one can go.', 'T. S. 엘리엇', 'T. S. Eliot'],
[' 그 여정이 바로 보상이다. ', 'The journey is the reward.', '스티브 잡스', 'Steve Jobs'],
[' 인간에게 유일한 위대함은 죽지 않는 것이다. ', 'The only greatness for man is immortality.', '제임스 딘', 'James Dean'],
[' 인생이 끝날까 두려워하지마라. 당신의 인생이 시작조차 하지 않을 수 있음을 두려워하라. ', "Don't be afraid your life will end; be afraid that it will never begin.", '그레이스 한센', 'Grace Hansen'],
[' 일단 당신이 성공을 위해 자신과 가족이 치뤄야 할 대가를 인정하면 사소한 아픔, 경쟁자의 압력, 일시적 실패는 감내할 수 있다. ', "Once you agree upon the price you and your family must pay for success, it enables you to ignore the minor hurts, the opponent's pressure, and the temporary failures.", '빈센트 롬바르디', 'Vincent Lombardi'],
[' 무릅써라! 그 어떤 위험도 무릅써라! 다른 이들의 말, 그들의 목소리에 더 이상 신경쓰지 마라. 세상에서 가장 어려운 것에 도전하라. 스스로 행동하라. 진실을 대면하라. ', 'Risk! Risk anything! Care no more for the opinions of others, for those voices. Do the hardest thing on earth for you. Act for yourself. Face the truth.', '캐서린 맨스필드', 'Katherine Mansfield'],
[' 주여, 제가 이룬 것보다 항상 더 많이 갈망하게 하소서. ', 'Lord, grant that I may always desire more than I accomplish.', '미켈란젤로', 'Michelangelo'],
[' 극히 조심한다는 방침이야말로 가장 위험한 것이다. ', 'The policy of being too cautious is the greatest risk of all.', '자와할랄 네루', 'Jawaharlal Nehru'],
[' 사람을 판단하는 최고의 척도는 안락하고 편안한 시기에 보여주는 모습이 아닌,도전하며 논란에 휩싸인 때 보여주는 모습이다. ', 'The ultimate measure of a person is not where they stand in moments of comfort and convenience, but where they stand in times of challenge and controversy.', '마틴 루터 킹', 'Martin Luther King Jr.'],
[' 천재는 거대한 인내일 뿐이다. ', 'Genius is nothing but a great capacity for patience.', '뷔퐁', 'Buffon'],
[' 어떤 일을 달성하기로 결심했으면 그 어떤 지겨움과 혐오감도 불사하고 완수하라. 고단한 일을 해낸 데서 오는 자신감은 실로 엄청나다. ', 'Having once decided to achieve a certain task, achieve it at all costs of tedium and distaste. The gain in self-confidence of having accomplished a tiresome labor is immense.', '아놀드 베넷', 'Arnold Bennett'],
[' 자신의 능력을 숨길 수 있는 것은 대단한 능력이다. ', "It is a great ability to be able to conceal one's ability.", '프랑수아 드 라 로슈푸코', 'Francois de La Rochefoucauld'],
[' 일부 천재가 비웃음을 샀다는 사실이 비웃음을 산 모든 사람이 천재라는 것을 의미하지는 않는다. 사람들은 콜럼버스를 비웃고, 풀턴을 비웃고, 라이트형제를 비웃었다. 그러나 사람들은 또한 보조라는 광대를 비웃었다. ', 'But the fact that some geniuses were laughed at does not imply that all who are laughed at are geniuses. They laughed at Columbus, they laughed at Fulton, they laughed at the Wright brothers. But they also laughed at Bozo the Clown.', '칼 세이건', 'Carl Sagan'],
[' 자신의 본성이 어떤 것이든 그에 충실 하라. 자신이 가진 재능의 끈을 놓아버리지 마라. 본성이 이끄는 대로 따르면 성공할 것이다. ', 'Whatever you are by nature, keep to it; never desert your line of talent. Be what nature intended you for and you will succeed.', '시드니 스미스', 'Sydney Smith'],
[' 그 투쟁에서 실패할 수도 있다는 개연성 때문에 정당하다고 믿는 대의를 지지하는 데서 물러 서서는 안된다. ', 'The probability that we may fail in the struggle ought not to deter us from the support of a cause we believe to be just.', '에이브러햄 링컨', 'Abraham Lincoln'],
[' 어떤 지적인 바보도 사물을 더 크고 보다 복잡하게 만들 수 있다. 그러나 그 반대 편으로 나아가기 위해서는 천재의 손길과 많은 용기가 필요하다. ', 'Any intelligent fool can make things bigger and more complex ... it takes a touch of genius -- and a lot of courage -- to move in the opposite direction.', '알버트 아인슈타인', 'Albert Einstein'],
[' 천재와 광인사이에는 아주 가느다란 선이 있다. 나는 이 선을 지웠다. ', "There's a fine line between genius and insanity. I have erased this line.", '오스카 레반트', 'Oscar Levant'],
[' 천재성에는 한계가 있을 수 있지만 어리석음에는 이런 장애가 없다. ', 'Genius may have its limitations, but stupidity is not thus handicapped.', '엘버트 허버드', 'Elbert Hubbard'],
[' 탁월하다는 것은 아는 것만으로는 충분치 않으며, 탁월해지기 위해, 이를 발휘하기 위해 노력해야 한다. ', 'With regard to excellence, it is not enough to know, but we must try to have and use it.', '아리스토텔레스', 'Aristotle'],
[' 자존심은 강력한 마약이지만, 자가면역 체계에는 별 도움이 되지 않는다. ', "Pride is a powerful narcotic, but it doesn't do much for the auto-immune system.", '스튜어트 스티븐스', 'Stuart Stevens'],
[' 실연당한 자신을 발견하는 것은 자존심에 상처가 된다. 잊기 위해 최선을 다하고, 그렇게 하지 못했다면 최소한 그런 척이라도 하라. ', "To find yourself jilted is a blow to your pride. Do your best to forget it and if you don't succeed, at least pretend to.", '몰리에르', 'Moliere'],
[' 누구도 본인의 동의없이 남을 지배할 만큼 훌륭하지는 않다 ', "No man is good enough to govern another man without that other's consent.", '에이브러햄 링컨', 'Abraham Lincoln'],
[' 자존심은 가장 고귀한 인격을 망친다. ', 'Pride sullies the noblest character.', '클라우디아누스', 'Claudianus'],
[' 가장 용감한 행동은 자신만을 생각하는 것이다. 큰 소리로. ', 'The most courageous act is still to think for yourself. Aloud.', '가브리엘(코코)샤넬', 'Gabriel Coco Chanel'],
[' 천재란 자신에게 주어진 일을 하는 재능 있는 사람일 뿐이다. ', 'A genius is just a talented person who does his homework.', '토마스 A. 에디슨', 'Thomas A. Edison'],
[' 내가 있는 곳이 낙원이라. ', 'Paradise is where I am.', '볼테르', 'Voltaire'],
[' 순교는 능력없이 유명해질 수 있는 유일한 방법이다. ', 'Martyrdom... is the only way in which a man can become famous without ability.', '조지 버나드 쇼', 'George Bernard Shaw'],
[' 천재성이란 그것의 소유자들을 온갖 곤경에 처하게 만드는 최상의 능력이라고 묘사할 수 있을 것이다. ', 'Genius might be described as a supreme capacity for getting its possessors into trouble of all kinds.', '사무엘 버틀러', 'Samuel Butler'],
[' 재능이 있거든 가능한 모든 방법으로 사용하라. 쌓아두지 마라. 구두쇠처럼 아껴 쓰지 마라. 파산하려는 백만장자처럼 아낌없이 써라. ', "If you have a talent, use it in every which way possible. Don't hoard it. Don't dole it out like a miser. Spend it lavishly like a millionaire intent on going broke.", '브렌단 프랜시스', 'Brendan Francis'],
[' 지금 공부 안 하면 더울 때 더운 데서 일하고 추울 때 추운 데서 일한다. ', "If you don't study now, you work in hot places when it's hot and work in cold places when it's cold.", '박명수', 'Park Myung Soo'],
[' 시작은 반이 아니라 시작일 뿐이다. ', "The beginning is not half, it is just the beginning.", '박명수', 'Park Myung Soo'],
[' 늦었다고 생각할때가 진짜 늦은거다. ', "It's really late when you think it's late.", '박명수', 'Park Myung Soo'],
[' "내 너 그럴 줄 알았다", 알았으면 제발 미리 말을 해줘라 ', '"I knew you would do that". If you knew, please tell me in advance', '박명수', 'Park Myung Soo'],
[' 어려운 길은 길이 아니다. ', "The hard way is not the way.", '박명수', 'Park Myung Soo'],
[' 새벽에 먹는 맥주와 치킨은 0칼로리. ', "Beer and chicken at dawn are zero calories.", '박명수', 'Park Myung Soo'],
[' 내일도 할 수 있는 일을 굳이 오늘 할 필요 없다. ', "You don't have to do what you can do tomorrow today.", '박명수', 'Park Myung Soo'],
[' 가는 말이 고우면 얕본다. ', "When a word is sweet, it looks down on you", '박명수', 'Park Myung Soo'],
[' 즐길 수 없으면 피하라. ', "If you can't enjoy it, avoid it.", '박명수', 'Park Myung Soo'],
[' 고생 끝에 골병 난다. ', "You will get sick after hard work.", '박명수', 'Park Myung Soo'],
[' 나까지 나설 필요 없다. ', "There's no need for me to step up.", '박명수', 'Park Myung Soo'],
[' 참을인 세번이면 호구. ', "If you endure it three times, you're a pushover.", '박명수', 'Park Myung Soo'],
[' 포기하면 편하다. ', "It's comfortable to give up.", '박명수', 'Park Myung Soo'],
[' 안되면 말고. ', "If it doesn't work, never mind.", '박명수', 'Park Myung Soo'],
[' 일찍 일어나는 새가 피곤하다. ', "The early bird is tired.", '박명수', 'Park Myung Soo'],
[' 일찍 일어나는 벌레는 잡아 먹힌다. ', "Early bird bugs are eaten.", '박명수', 'Park Myung Soo'],
[' 성공은 1% 재능과 99% 빽. ', "Success is 1% talent and 99% well-connection.", '박명수', 'Park Myung Soo'],
[' 하나를 보고 열을 알면 무당. ', "If you see one and know ten, you're a shaman.", '박명수', 'Park Myung Soo'],
[' 원수는 회사에서 만난다. ', "The enemy meets at work.", '박명수', 'Park Myung Soo'],
[' 티끌 모아 티끌 ', "A lot of dust. A lot of dust", '박명수', 'Park Myung Soo'],
]

#출처 : 네이버 명언 